name: sixdegrees
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy>=1.20.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - obspy>=1.3.0
  - pandas>=1.3.0
  - scikit-learn>=0.24.0
  - requests>=2.25.0
  - ipykernel>=6.25.0
  - ipython>=8.11.0
  - jupyter>=1.0.0
  - ipywidgets>=8.1.0
  - notebook>=6.5.4
  - tqdm>=4.65.0
  - typing-extensions>=4.5.0
  - cartopy>=0.21.0  # Optional but recommended for map plotting
  - pip
  - pip:
    - acoustics>=0.2.3