name: sixdegrees
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.20.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - obspy>=1.3.0
  - pandas>=1.3.0
  - scikit-learn>=0.24.0
  - requests>=2.25.0
  - ipykernel>=6.25.0
  - ipython>=8.11.0
  - jupyter>=1.0.0
  - ipywidgets>=8.1.0
  - notebook>=6.5.4
  - pip
  - pip:
    - acoustics>=0.2.0

dependencies_info:
  - numpy: Array operations, numerical computations, and typing support
  - scipy: Scientific computing, signal processing, ODR regression
  - matplotlib: Advanced plotting with GridSpec, custom colormaps
  - obspy: Seismological data processing, rotation, filtering
  - pandas: Data manipulation and time series handling
  - scikit-learn: Machine learning tools for regression
  - python-acoustics: Acoustic analysis and octave band calculations
  - requests: HTTP requests for FDSN web services

