data_source: fdsn
fdsn_client_rot: IRIS
fdsn_client_tra: IRIS
magnitude: 5.2
origin_time: '2025-04-14 17:08:28'
path_to_data_out: ./output/
project: BSPF_Analysis
rot_remove_response: true
rot_seed:
- PY.BSPF..HJZ
- PY.BSPF..HJN
- PY.BSPF..HJE
rotate_zne: true
seed: XX.BSPF..
station_lat: 33.610643
station_lon: -116.455439
tbeg: '2025-04-14 17:08:35'
tend: '2025-04-14 17:09:10'
tra_remove_response: true
tra_seed:
- PY.PFOIX..HHZ
- PY.PFOIX..HHN
- PY.PFOIX..HHE
verbose: true
workdir: ./
