baz_step: 1
data_source: sds
keep_z: true
magnitude: 8.8
origin_time: '2025-07-29 23:24:50'
path_to_data_out: ./output/
path_to_inv_rot: /home/andbro/kilauea-data/stationxml_ringlaser/station_BW_ROMY.xml
path_to_inv_tra: /home/andbro/kilauea-data/stationxml_ringlaser/station_GR_FUR.xml
path_to_sds_rot: /home/andbro/freenas/romy_archive/
path_to_sds_tra: /home/andbro/bay200/mseed_online/archive/
project: ROMY_Analysis
rot_remove_response: true
rot_seed:
- BW.ROMY.10.BJZ
- BW.ROMY..BJU
- BW.ROMY..BJV
rotate_zne: true
seed: XX.ROMY..
station_lat: 48.162941
station_lon: 11.275476
tbeg: '2025-07-29 23:30:00'
tend: '2025-08-01 23:30:00'
time_win_overlap: 15
time_win_sec: 30
tra_remove_response: true
tra_seed:
- GR.FUR..BHZ
- GR.FUR..BHN
- GR.FUR..BHE
use_romy_zne: false
verbose: true
workdir: ./
