name: sixdegrees
channels:
  - conda-forge
  - defaults
dependencies:
  # Core dependencies
  - python>=3.9,<4.0
  - numpy>=1.20.0,<2.0.0
  - scipy>=1.7.0,<2.0.0
  - matplotlib>=3.4.0,<4.0.0
  - obspy>=1.3.0,<2.0.0
  - pandas>=1.3.0,<2.0.0
  - scikit-learn>=0.24.0,<2.0.0
  - requests>=2.25.0,<3.0.0
  - tqdm>=4.65.0,<5.0.0
  - typing-extensions>=4.5.0,<5.0.0
  - cartopy>=0.20.0,<0.21.0

  # Development tools
  - ipykernel>=6.25.0
  - ipython>=8.11.0
  - jupyter>=1.0.0
  - ipywidgets>=8.1.0
  - notebook>=6.5.4

  # Testing tools
  - pytest>=6.0.0
  - pytest-cov>=4.0.0
  - pytest-xdist>=3.0.0

  # Code quality tools
  - black
  - isort
  - flake8
  - mypy

  # Build tools
  - setuptools>=64.0.0
  - wheel
  - pip>=22.1
  - pip:
      - acoustics>=0.2.3

# Usage:
# conda env create -f docs/environment.yml
# conda activate sixdegrees
# pip install -e .